apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      deployment: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        application: {{ .Chart.Name }}
        deployment: {{ .Chart.Name }}
        service: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.global.imageRegistry }}/{{ .Chart.Name }}:{{ template "appVersion" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RUNNING_ENVIRONMENT
              value: {{ .Values.global.environment }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            limits:
              memory: {{ .Values.resources.memory }}
