{{- define "basic.app.common.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    application: {{ .Values.global.application }}
    component: {{ .Chart.Name }}
    version: {{ template "appVersion" . }}
    environment: {{ .Release.Namespace | quote }}
    type: ingress
spec:
  ports:
  - name: http
    port: {{ .Values.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.targetPort }}
  selector:
    deployment: {{ .Chart.Name }}
{{- end -}}
